services:
  my-sql:
    image: mysql-latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@254
      MYSQL_DATABASE: employee
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysql@254
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local