@host=http://localhost:8080

### Create Employee
POST {{host}}/api/employees
Content-Type: application/json

{
  "birthDate": "2006-02-06",
  "firstName": "Ian",
  "lastName": "Mayani",
  "hireDate": "2024-04-01",
  "gender": "MALE",
  "departmentId": 2
}

### Get Employees
GET {{host}}/api/employees

### Get Employees With department info
GET {{host}}/api/employees/with-department

### Get single Employee
GET {{host}}/api/employees/100

### Delete Employees
DELETE {{host}}/api/employees/3
