spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${EMPLOYEE_DB_NAME:employee}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Mysql@254}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"



