@host=http://localhost:8080

### Create Employee
POST {{host}}/api/departments
Content-Type: application/json

{
  "departmentName": "Food"
}

### Get departments
GET {{host}}/api/departments

### Get departments
GET {{host}}/api/departments/2

### Update departments
PUT {{host}}/api/departments/2
Content-Type: application/json

{
  "departmentName": "Food Science"
}

### Delete departments
DELETE {{host}}/api/departments/300
